-- ============================================================
-- Audit Management System — Database Schema
-- Compatible with MySQL 8.x (H2 is auto-generated by JPA)
-- ============================================================

CREATE DATABASE IF NOT EXISTS auditdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE auditdb;

-- ===== USERS =====
CREATE TABLE users (
    id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    username    VARCHAR(50)  NOT NULL UNIQUE,
    email       VARCHAR(100) NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    role        ENUM('ADMIN','AUDITOR','CLIENT') NOT NULL DEFAULT 'CLIENT',
    created_at  DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- ===== AUDIT RECORDS =====
CREATE TABLE audit_records (
    id                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id             BIGINT NOT NULL,
    company_name        VARCHAR(200) NOT NULL,
    audit_type          ENUM('FINANCIAL','SECURITY','COMPLIANCE') NOT NULL,
    number_of_employees INT,
    has_firewall        BOOLEAN DEFAULT FALSE,
    has_antivirus       BOOLEAN DEFAULT FALSE,
    has_encryption      BOOLEAN DEFAULT FALSE,
    has_mfa             BOOLEAN DEFAULT FALSE,
    previous_incidents  BOOLEAN DEFAULT FALSE,
    compliance_level    ENUM('LOW','MEDIUM','HIGH') NOT NULL,
    data_sensitivity    ENUM('LOW','MEDIUM','HIGH','CRITICAL') NOT NULL,
    update_frequency    ENUM('RARELY','MONTHLY','WEEKLY','DAILY') NOT NULL,
    risk_score          INT,
    risk_level          ENUM('LOW','MEDIUM','HIGH','CRITICAL'),
    recommendations     TEXT,
    submitted_at        DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_risk_level (risk_level),
    INDEX idx_user_id (user_id),
    INDEX idx_submitted_at (submitted_at)
);

-- ===== SAMPLE DATA =====
INSERT INTO users (username, email, password, role) VALUES
('admin',    'admin@auditpro.com',    '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'ADMIN'),
('auditor1', 'auditor@auditpro.com',  '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'AUDITOR'),
('client1',  'client@company.com',    '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'CLIENT');
-- Note: passwords above are BCrypt hash of "admin123" / "audit123" / "client123"
-- Use the seeder in AuditApplication.java for H2 demo

INSERT INTO audit_records
  (user_id, company_name, audit_type, number_of_employees,
   has_firewall, has_antivirus, has_encryption, has_mfa,
   previous_incidents, compliance_level, data_sensitivity, update_frequency,
   risk_score, risk_level, recommendations)
VALUES
(1, 'TechCorp Solutions', 'SECURITY', 250,
 FALSE, TRUE, FALSE, FALSE, TRUE,
 'LOW', 'HIGH', 'MONTHLY',
 65, 'HIGH',
 'Enable MFA||Implement encryption||Improve compliance posture'),

(2, 'FinanceHub Ltd', 'FINANCIAL', 80,
 TRUE, TRUE, TRUE, TRUE, FALSE,
 'HIGH', 'CRITICAL', 'WEEKLY',
 15, 'LOW',
 'Security posture is strong. Continue regular audits.'),

(3, 'RetailMax Inc', 'COMPLIANCE', 500,
 FALSE, FALSE, FALSE, FALSE, TRUE,
 'LOW', 'MEDIUM', 'RARELY',
 88, 'CRITICAL',
 'Deploy firewall||Install antivirus||Enable MFA||Implement encryption||Establish patch schedule'),

(1, 'MedData Systems', 'SECURITY', 120,
 TRUE, TRUE, TRUE, FALSE, FALSE,
 'MEDIUM', 'CRITICAL', 'WEEKLY',
 37, 'MEDIUM',
 'Enable MFA||Implement DLP for critical data');
